blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/AlvinCoded/laravel-mtn-momo-ai/discussions
    about: Ask questions and discuss with other community members
